<?php

/**
 * @file
 * The OpenEuropa List Pages module.
 */

declare(strict_types = 1);

/**
 * Implements hook_facets_search_api_query_type_mapping_alter().
 */
function oe_list_pages_facets_search_api_query_type_mapping_alter($backend_plugin_id, array &$query_types) {
  // We need to define a new query type to be used by full text list facets,
  // which will apply query logic required for text search.
  $query_types['fulltext_comparison'] = 'fulltext_query_type';
  $query_types['date_comparison'] = 'date_query_type';
  $query_types['oe_list_pages_date_status_comparison'] = 'oe_list_pages_date_status_query_type';
}

/**
 * Implements hook_theme().
 */
function oe_list_pages_theme($existing, $type, $theme, $path) {
  return [
    'oe_list_pages_selected_facet' => [
      'variables' => [
        'items' => [],
        'label' => NULL,
      ],
    ],
    'oe_list_pages_rss' => [
      'variables' => [
        'title' => '',
        'link' => '',
        'description' => '',
        'language' => '',
        'copyright' => '',
        'image' => [],
        'channel_elements' => [],
        'items' => [],
      ],
    ],
    'oe_list_pages_rss_item' => [
      'variables' => [
        'title' => '',
        'link' => '',
        'guid' => '',
        'description' => '',
        'item_elements' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function oe_list_pages_locale_translation_projects_alter(&$projects) {
  $projects['oe_list_pages']['info']['interface translation server pattern'] = drupal_get_path('module', 'oe_list_pages') . '/translations/%project-%language.po';
}
