facet.widget.config.oe_list_pages_fulltext:
  type: facet.widget.default_config
  label: 'Fulltext widget configuration'
  mapping:
    fulltext_all_fields:
      type: boolean
      label: 'Search on all fulltext fields'
    placeholder:
      type: label
      label: 'Placeholder'

facet.widget.config.oe_list_pages_date:
  type: facet.widget.default_config
  label: 'Date widget configuration'
  mapping:
    date_type:
      type: string
      label: 'Date type of date facet widget'

facet.widget.config.oe_list_pages_multiselect:
  type: facet.widget.default_config
  label: 'Multiselect widget configuration'
  mapping:
    placeholder:
      type: label
      label: 'Placeholder'
